### ISSUE TITLE
Use `node-byline` from npm

### ISSUE THREAD

**Issue by blond** [arikon/bower-npm-install#16]
Every time I install this package, I see the following warning:

```console
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/SevInf/node-byline.git)
```

Is there any reason to not use npm?

**Comment by arikon** [comment]
@andrewblond We were using patched node-byline, that was working on node 0.8. I think we can switch to npm hosted one.

/cc @SevInf
